# Generated by Django 4.1.6 on 2023-02-13 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiederModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magic_number', models.IntegerField(default=7777777)),
                ('email', models.CharField(max_length=255)),
                ('login', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
                ('terminal_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Лидер',
                'verbose_name_plural': 'Лидер',
            },
        ),
        migrations.CreateModel(
            name='InvestorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('login', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('server', models.CharField(max_length=255)),
                ('terminal_path', models.CharField(max_length=255)),
                ('active_action', models.BooleanField(default=True)),
                ('investment_size', models.FloatField(default=10000.0, verbose_name='Стартовый капитал')),
                ('transaction_plus', models.FloatField(default=0.1, verbose_name='Сделка в +')),
                ('transaction_minus', models.FloatField(default=-0.1, verbose_name='Сделка в -')),
                ('transaction_timeout', models.IntegerField(default=1, verbose_name='Время ожидания')),
                ('transaction_type', models.CharField(choices=[('Все', 'Все'), ('Плюс', 'Плюс'), ('Минус', 'Минус')], default='Все', max_length=100, verbose_name='Спросить у инвестора')),
                ('transaction_action', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=100, verbose_name='Возврат цены')),
                ('initiator', models.CharField(choices=[('Инвестор', 'Инвестор'), ('Админ', 'Админ'), ('Система', 'Система')], default='Инвестор', max_length=100, verbose_name='Инициатор')),
                ('disconnect', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=100, verbose_name='Отключиться')),
                ('w_positions', models.CharField(choices=[('Закрыть', 'Закрыть'), ('Оставить', 'Оставить')], default='Закрыть', max_length=100, verbose_name='Открытые сделки')),
                ('notify', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=100, verbose_name='Уведомления')),
                ('in_blacklist', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=100, verbose_name='Блеклист')),
                ('after', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=100, verbose_name='Сопровождать сделки')),
                ('multiplier_type', models.CharField(choices=[('Средства', 'Средства'), ('Баланс', 'Баланс')], default='Баланс', max_length=100, verbose_name='Множитель')),
                ('volume_multiplier', models.FloatField(default=1.0, verbose_name='Значение множителя')),
                ('change_multiplier', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=100, verbose_name='Изменение множителя')),
                ('stop_limit_type', models.CharField(choices=[('Средства', 'Средства'), ('Проценты', 'Проценты')], default='Проценты', max_length=100, verbose_name='Стоп-лосс')),
                ('volume_stop_limit', models.FloatField(default=20.0, verbose_name='Значение стопа')),
                ('stop_limit_after', models.CharField(choices=[('Закрыть', 'Закрыть'), ('Закрыть и отключить', 'Закрыть и отключить')], default='Закрыть', max_length=100, verbose_name='Открытые сделки')),
                ('lieder', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_mt.liedermodel', verbose_name='Лидер')),
            ],
            options={
                'verbose_name': 'Инвестор',
                'verbose_name_plural': 'Инвестор',
            },
        ),
    ]
